# Generated by Django 5.1.2 on 2024-10-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_del_rentador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "numero_de_celular_rentador",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Número de teléfono del usuario",
                        null=True,
                    ),
                ),
                ("pago_renta", models.BooleanField(default=False)),
                (
                    "fecha_de_evento",
                    models.DateField(
                        blank=True, help_text="Indica la fecha del eventp", null=True
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Indica cualquier información referente al evento",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "eventos",
                "ordering": ["pk"],
                "permissions": [
                    ["autorizar_evento", "Puede Autorizar Eventos"],
                    ["viewcrud_evento", "Puede Visualizar Eventos en el menú"],
                ],
            },
        ),
    ]
