# Generated by Django 5.1.2 on 2024-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prueba", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_entrada", models.DateTimeField(blank=True, null=True)),
                ("hora_salida", models.DateTimeField(blank=True, null=True)),
                (
                    "llego_tarde",
                    models.BooleanField(
                        default=False,
                        help_text="Si llego 15 min tarde se va a recorrer 1 hora su registro",
                    ),
                ),
                (
                    "se_cancela_su_dia",
                    models.BooleanField(
                        default=False,
                        help_text="llego 2 horas tarde se va va a cancelar el dia",
                    ),
                ),
                (
                    "estado_registro",
                    models.CharField(
                        choices=[("A", "Aprobada"), ("C", "Cancelada")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro De Horario",
                "verbose_name_plural": "Registros De Horarios",
                "db_table": "registros_de_horas",
                "ordering": ["pk"],
                "permissions": [
                    ["autorizar_registrohora", "Puede Autorizar Registros De Horarios"],
                    [
                        "viewcrud_registrohora",
                        "Puede Visualizar Registros De Horarios en el menú",
                    ],
                ],
            },
        ),
        migrations.CreateModel(
            name="SolicitudJustificante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_solicitud",
                    models.CharField(
                        choices=[
                            ("A", "Aprobada"),
                            ("R", "Rechazada"),
                            ("P", "Pendiente"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        help_text="Motivo por la cual se va a justificar",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "dia_justificar",
                    models.DateField(
                        blank=True, help_text="Dia que quiere justificar", null=True
                    ),
                ),
                (
                    "clave_empleado",
                    models.IntegerField(
                        blank=True,
                        help_text="Clave del empleado que quiere justificar",
                        null=True,
                    ),
                ),
                ("evidencia_pdf", models.FileField(upload_to="documentos_pdfs/")),
            ],
            options={
                "verbose_name": "Solicitud de justificante",
                "verbose_name_plural": "Solicitudes de justificantes",
                "db_table": "solicitudes_justificantes",
                "ordering": ["pk"],
                "permissions": [
                    [
                        "autorizar_solicitudjustificane",
                        "Puede Autorizar Solicitudes de justificantes",
                    ],
                    [
                        "viewcrud_solicitudjustificane",
                        "Puede Visualizar Solicitudes de justificantes en el menú",
                    ],
                ],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del usuario",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "clave",
                    models.IntegerField(
                        blank=True, help_text="Clave que se usara de Acceso", null=True
                    ),
                ),
                (
                    "es_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Booleano que indica si el usuario es admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["pk"],
                "permissions": [
                    ["autorizar_usuario", "Puede Autorizar Usuarios"],
                    ["viewcrud_usuario", "Puede Visualizar Usuarios en el menú"],
                ],
            },
        ),
    ]
