# Generated by Django 5.1.2 on 2024-10-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prueba", "0002_registrohorario_solicitudjustificante_usuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Evento",
        ),
        migrations.AddField(
            model_name="registrohorario",
            name="clave_empleado",
            field=models.IntegerField(
                blank=True,
                help_text="Clave del empleado que registra su horas",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registrohorario",
            name="usuario_que_registra",
            field=models.ForeignKey(
                blank=True,
                help_text="Relacion al empleaod que hizo el registro, se va a relacionar con la clave que se ortorga ",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="registros_de_horas",
                to="prueba.usuario",
            ),
        ),
        migrations.AddField(
            model_name="solicitudjustificante",
            name="usuario_que_registra",
            field=models.ForeignKey(
                blank=True,
                help_text="Relacion al empleaod que hizo el justificante, se va a relacionar con la clave que se ortorga ",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="solicitudes_justificantes",
                to="prueba.usuario",
            ),
        ),
    ]
