# Generated by Django 5.1.2 on 2024-11-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_registrohorario_total_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
