# Generated by Django 5.1.2 on 2024-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prueba", "0003_delete_evento_registrohorario_clave_empleado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Contraseña encriptada del usuario administrador",
                max_length=128,
                null=True,
            ),
        ),
    ]
