# Generated by Django 5.1.2 on 2024-11-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_remove_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(blank=True, help_text='Contraseña de usuario pa la movida esa', max_length=200, null=True),
        ),
    ]
