# Generated by Django 5.1.2 on 2024-11-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_usuario_contrasenia'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
