# Generated by Django 5.1.2 on 2024-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prueba", "0004_usuario_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="clave",
            field=models.IntegerField(
                blank=True,
                help_text="Clave que se usara de Acceso",
                null=True,
                unique=True,
            ),
        ),
    ]
