# Generated by Django 5.1.2 on 2024-10-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prueba", "0005_alter_usuario_clave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrohorario",
            name="estado_registro",
            field=models.CharField(
                choices=[("A", "Aprobada"), ("C", "Cancelada"), ("T", "En Transcurso")],
                max_length=1,
            ),
        ),
    ]
