# Generated by Django 5.1.2 on 2024-11-04 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prueba", "0006_alter_registrohorario_total_horas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrohorario",
            name="usuario_que_registra",
            field=models.ForeignKey(
                blank=True,
                help_text="Relacion al empleaod que hizo el registro, se va a relacionar con la clave que se ortorga ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros_de_horas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudjustificante",
            name="usuario_que_registra",
            field=models.ForeignKey(
                blank=True,
                help_text="Relacion al empleaod que hizo el justificante, se va a relacionar con la clave que se ortorga ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes_justificantes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
